### ISSUE TITLE
项目运行环境

### ISSUE THREAD

**Issue by CUGWLZ713** [Unagi-cq/THChatUI#1]
此项目可以在Windows环境想运行吗？

**Comment by Unagi-cq** [comment]
完全可以。

先在电脑上安装好node，然后到thchat-ui目录下运行以下代码就能启动前端：
`
npm install
npm run serve
`
然后去申请模型的key，填入设置即可。

如果想使用本地的接口，参考项目的readme在thchat-server目录下运行指定的文件也是可以的。如果不是linux环境部署是不需要额外配置nginx的。
